// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRUPCih_22BdO0IiIvoecvyv37uNqTfo',
    appId: '1:666325417376:web:9fc22bad14f5590b0378c5',
    messagingSenderId: '666325417376',
    projectId: 'hsm-test2-flutter-5423543',
    authDomain: 'hsm-test2-flutter-5423543.firebaseapp.com',
    storageBucket: 'hsm-test2-flutter-5423543.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDKyKiupTxOwwV4PudVtoqIFu3Np2ksGQ',
    appId: '1:666325417376:android:4194cc0e562cc0a40378c5',
    messagingSenderId: '666325417376',
    projectId: 'hsm-test2-flutter-5423543',
    storageBucket: 'hsm-test2-flutter-5423543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP0gShGNPnaH_LMUwvZu-Qf1W3dk4_-Vw',
    appId: '1:666325417376:ios:94a08d1dcc600b1a0378c5',
    messagingSenderId: '666325417376',
    projectId: 'hsm-test2-flutter-5423543',
    storageBucket: 'hsm-test2-flutter-5423543.appspot.com',
    iosClientId: '666325417376-1i8u97tsfl32b22evsavdtsoojq1l2um.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP0gShGNPnaH_LMUwvZu-Qf1W3dk4_-Vw',
    appId: '1:666325417376:ios:94a08d1dcc600b1a0378c5',
    messagingSenderId: '666325417376',
    projectId: 'hsm-test2-flutter-5423543',
    storageBucket: 'hsm-test2-flutter-5423543.appspot.com',
    iosClientId: '666325417376-1i8u97tsfl32b22evsavdtsoojq1l2um.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
